apiVersion: v1
kind: Service
metadata:
  name: parkshare-web
  labels:
    app.kubernetes.io/name: parkshare
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: parkshare
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 8000
